config/routes.rb
VandyMobileWeb::Application.routes.draw do

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users

  resources :meetings
  
  resources :teams
  
  resources :apps

  get "home/index"

  root :to => 'home#index'

end

app/models/meeting.rb
class Meeting < ActiveRecord::Base
  attr_accessible :date, :day, :xcoordinate, :ycoordinate, :food, :speaker, :speaker_name, :topic, :description, :user_ids
  validates_presence_of :date, :day
  
  has_many :meeting_assignments
  has_many :users, through: :meeting_assignments
end

app/controllers/meetings_controller.rb
class MeetingsController < ApplicationController
  # GET /meetings
  # GET /meetings.json
  def index
    @meetings = Meeting.order(:date)
    expires_in 10.second, :public => true
    if stale?(:etag => @meeting)
	    respond_to do |format|
	      format.html # index.html.erb
	      format.json { render json: @meetings.where("date > ?", Time.now).to_json(:include => {:users => {:only => :email}})}
 	    end
	end

  end

  # GET /meetings/1
  # GET /meetings/1.json
  def show
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @meeting }
    end
  end

  # GET /meetings/new
  # GET /meetings/new.json
  def new
	if params[:day]
		@meeting = Meeting.create(:day => params[:day], :date => params[:date])
	else
    	@meeting = Meeting.new
    end
  end

  # GET /meetings/1/edit
  def edit
    @meeting = Meeting.find(params[:id])
  end

  # POST /meetings
  # POST /meetings.json
  def create
    @meeting = Meeting.new(params[:meeting])

    respond_to do |format|
      if @meeting.save
        format.html { redirect_to @meeting, notice: 'Meeting was successfully created.' }
        format.json { render json: @meeting, status: :created, location: @meeting }
      else
        format.html { render action: "new" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /meetings/1
  # PUT /meetings/1.json
  def update
    @meeting = Meeting.find(params[:id])

    respond_to do |format|
      if @meeting.update_attributes(params[:meeting])
        format.html { redirect_to @meeting, notice: 'Meeting was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @meeting.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meetings/1
  # DELETE /meetings/1.json
  def destroy
    @meeting = Meeting.find(params[:id])
    @meeting.destroy

    respond_to do |format|
      format.html { redirect_to meetings_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/meetings_helper.rb
module MeetingsHelper
end

app/views/meetings/_form.html.erb
<%= form_for(@meeting) do |f| %>
  <% if @meeting.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@meeting.errors.count, "error") %> prohibited this meeting from being saved:</h2>

      <ul>
      <% @meeting.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :day %><br />
    <%= f.select :day, ['Monday', 'Tuesday', 'Wednesday', 'Thursday', 'Friday', 'Saturday', 'Sunday'] %>
  </div>
  <div class="field">
    <%= f.label :date %><br />
    <%= f.datetime_select :date %>
  </div>
  <div class="field">
    <%= f.label :xcoordinate %><br />
    <%= f.text_field :xcoordinate %>
  </div>
  <div class="field">
    <%= f.label :ycoordinate %><br />
    <%= f.text_field :ycoordinate %>
  </div>
  <div class="field">
    <%= f.label :food %><br />
    <%= f.check_box :food %>
  </div>
  <div class="field">
    <%= f.label :speaker %><br />
    <%= f.check_box :speaker %>
  </div>
  <div class="field">
    <%= f.label :speaker_name %><br />
    <%= f.text_field :speaker_name %>
  </div>
  <div class="field">
    <%= f.label :topic %><br />
    <%= f.text_field :topic %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div> 
  <div class="field">
    <% @user = User.all %><br />
    <%= f.label :users %><br />
    <%= f.select :user_ids, User.all.collect {|x| [x.email, x.id]}, {}, :multiple => true %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/meetings/edit.html.erb
<h1>Editing meeting</h1>

<%= render 'form' %>

<%= link_to 'Show', @meeting %> |
<%= link_to 'Back', meetings_path %>

app/views/meetings/index.html.erb
<h1>Listing meetings</h1>

<table>
  <tr>
    <th>Day</th>
    <th>Date</th>
    <th>Xcoordinate</th>
    <th>Ycoordinate</th>
    <th>Food</th>
    <th>Speaker</th>
    <th>Speaker name</th>
    <th>Topic</th>
    <th>Description</th>    
    <th>Users</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @meetings.each do |meeting| %>
  <tr>
    <td><%= meeting.day %></td>
    <td><%= meeting.date %></td>
    <td><%= meeting.xcoordinate %></td>
    <td><%= meeting.ycoordinate %></td>
    <td><%= meeting.food %></td>
    <td><%= meeting.speaker %></td>
    <td><%= meeting.speaker_name %></td>
    <td><%= meeting.topic %></td>
    <td><%= meeting.description %></td>
    <% if meeting.users.exists? %>
    	<% meeting.users.each do |user| %>
    		<td><%= user.email %></td>
    	<% end %>
    <% else %>
		<td><%= "N/A" %></td>	
	<% end %>
    <td><%= link_to 'Show', meeting %></td>
    <td><%= link_to 'Edit', edit_meeting_path(meeting) %></td>
    <td><%= link_to 'Destroy', meeting, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Meeting', new_meeting_path %>

app/views/meetings/new.html.erb
<h1>New meeting</h1>

<%= render 'form' %>

<%= link_to 'Back', meetings_path %>

app/views/meetings/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Day:</b>
  <%= @meeting.day %>
</p>

<p>
  <b>Date:</b>
  <%= @meeting.date %>
</p>

<p>
 <b>xcoordinate:</b>
 <%= @meeting.xcoordinate %>
</p>

<p>
 <b>ycoordinate:</b>
 <%= @meeting.ycoordinate %>
</p>

<p>
  <b>Food:</b>
  <%= @meeting.food %>
</p>

<p>
  <b>Speaker:</b>
  <%= @meeting.speaker %>
</p>

<p>
  <b>Speaker name:</b>
  <%= @meeting.speaker_name %>
</p>

<p>
  <b>Topic:</b>
  <%= @meeting.topic %>
</p>

<p>
  <b>Description:</b>
  <%= @meeting.description %>
</p>

<p>
  <b>Users:</b>
  <% if @meeting.users.exists? %>
  	<% @meeting.users.each do |user| %>
    	<td><%= user.email %></td>
    <% end %>
    <% else %>
		<td><%= "N/A" %></td>	
	<% end %>
</p>

<%= link_to 'Edit', edit_meeting_path(@meeting) %> |
<%= link_to 'Back', meetings_path %>