config/routes.rb
VandyMobileWeb::Application.routes.draw do

  match 'user/edit' => 'users#edit', :as => :edit_current_user

  match 'signup' => 'users#new', :as => :signup

  match 'logout' => 'sessions#destroy', :as => :logout

  match 'login' => 'sessions#new', :as => :login

  resources :sessions

  resources :users

  resources :meetings
  
  resources :teams
  
  resources :apps

  get "home/index"

  root :to => 'home#index'

end

app/views/apps/_form.html.erb
<%= form_for(@app) do |f| %>
  <% if @app.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@app.errors.count, "error") %> prohibited this app from being saved:</h2>

      <ul>
      <% @app.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  
  <div class="field">
    <%= f.label :team %><br />
    <%= f.select :team_id, Team.all.collect {|x| [x.name, x.id]}, {}%>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :os %><br />
    <%= f.text_field :os %>
  </div>
  <div class="field">
    <%= f.label :tagline %><br />
    <%= f.text_area :tagline %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </div>
  <div class="field">
    <%= f.label :image_url %><br />
    <%= f.text_field :image_url %>
  </div>
  <div class="field">
    <%= f.label :app_url %><br />
    <%= f.text_field :app_url %>
  </div>
   <div class="field">
    <%= f.label :repo_url %><br />
    <%= f.text_field :repo_url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/apps/edit.html.erb
<h1>Editing app</h1>

<%= render 'form' %>

<%= link_to 'Show', @app %> |
<%= link_to 'Back', apps_path %>

app/views/apps/index.html.erb
<h1>Listing apps</h1>

<table>
  <tr>
  	<th>Team</th>
    <th>Name</th>
    <th>OS</th>
    <th>Tagline</th>
    <th>Description</th>
    <th>ImageURL</th>
    <th>AppURL</th>
    <th>RepoURL</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @apps.each do |app| %>
  <tr>
    <% if app.team %>
    	<td><%= app.team.name %></td>
    <% else %>
    	<td><%= "N/A" %></td>
    <% end %>
    <td><%= app.name %></td>
    <td><%= app.os %></td>
    <td><%= app.tagline %></td>
    <td><%= app.description %></td>
    <td><%= app.image_url %></td>
    <td><%= app.app_url %></td>
    <td><%= app.repo_url %></td>
    <td><%= link_to 'Show', app %></td>
    <td><%= link_to 'Edit', edit_app_path(app) %></td>
    <td><%= link_to 'Destroy', app, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New App', new_app_path %>

app/views/apps/new.html.erb
<h1>New app</h1>

<%= render 'form' %>

<%= link_to 'Back', apps_path %>

app/views/apps/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @app.name %>
</p>

<p>
  <b>OS:</b>
  <%= @app.os %>
</p>

<p>
  <b>Tagline:</b>
  <%= @app.tagline %>
</p>

<p>
  <b>Description:</b>
  <%= @app.description %>
</p>


<p>
  <b>Image URL:</b>
  <%= @app.image_url %>
</p>

<p>
  <b>App URL:</b>
  <%= @app.app_url %>
</p>

<p>
  <b>Repo URL:</b>
  <%= @app.repo_url %>
</p>




<%= link_to 'Edit', edit_app_path(@app) %> |
<%= link_to 'Back', apps_path %>